name: Docs - Preview Deployment - TEST
on:
    pull_request:
        paths:
            - sites/docs/**
            - packages/bits-ui/**

# cancel in-progress runs on new commits to same PR (github.event.number)
concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
    deploy-preview:
        permissions:
            contents: read
            pull-requests: write
            deployments: write
        runs-on: ubuntu-latest
        name: Deploy Preview to Cloudflare Pages
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 20

            # PNPM Store cache setup
            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Build site
              run: pnpm build

            - name: Deploy to Cloudflare Pages
              id: cloudflare-pages-deploy
              uses: AdrianGonz97/refined-cf-pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: bits-ui
                  directory: ./.svelte-kit/cloudflare
                  workingDirectory: sites/docs
                  deploymentName: Preview
