name: Publish Preview Release
on:
    label:
    pull_request:
        paths: packages/**

jobs:
    preview-release:
        if: github.repository == 'huntabyte/bits-ui'
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: install dependencies
              run: pnpm install

            - name: build
              run: pnpm build:packages

            - name: publish preview
              run: |
                  pnpx pkg-pr-new@0.0 publish --pnpm './packages/*'
